### PR TITLE
Use simple bind method if LDAP accepts anonymous bind

### PR DESCRIPTION
**Pull request by DmitriyLyalyuev**

### CODE REVIEW

**Comment by vl-homutov** [comment]
wouldn't it be just enough to remove default for binddn at line 147? this should results in binding with empty name and password, i.e. anonymous bind, as desired. Currently omitting binddn in configuration leads to 'unauthenticated bind' (cn=anonymous and empty password), which is usually disabled by default (at least in openldap).

**Comment by DmitriyLyalyuev** [comment]
I tested with cn=anonymous with no password and got this error:
Error while binding as search user: {'info': 'unauthenticated bind (DN with no password) disallowed', 'desc': 'Server is unwilling to perform'}, server="ldap://127.0.0.1:389"

Now tested with 
'binddn': ('X-Ldap-BindDN', ''),
and this working fine.

May be should binddn be set to '' as default?

**Comment by vl-homutov** [comment]
yes, this is the correct solution.

**Comment by DmitriyLyalyuev** [comment]
Second commit edit this. 
Can you apply PR or I should ammend commits with correct thing.

**Comment by vl-homutov** [comment]
I'll just commit the fix later by myself.

**Comment by DmitriyLyalyuev** [comment]
Ok. Thanks.

**Pull request closed without merging**
